services:
  web:
#    image: php:8.3-apache
    build: ./imagenes/.
    ports:
      - 8800:80
    volumes:
      - ./../app:/var/www/html
    container_name: web
  mysql:
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql
    enviroment:
        - MYSQL_ROOT_PASSWORD=lucas123
        - MYSQL_USER=alumno
        - MYSQL_PASSWORD=alumno
        - MYSQL_DATABASE=tienda
#    ports:
#      - 33306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8100:80
    enviroment:
      - PMA_HOST = mysql
      - PMA_ARBITRARY = 1
    depends_on:  
     - mysql